package Sem6Lab5;


/**
* Sem6Lab5/TaskableOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sem6Lab5.idl
* 12 апреля 2019 г. 14:19:27 MSK
*/

public interface TaskableOperations 
{
  String getResult ();
} // interface TaskableOperations
