package Sem6Lab5;

/**
* Sem6Lab5/TaskableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sem6Lab5.idl
* 12 апреля 2019 г. 14:19:27 MSK
*/

public final class TaskableHolder implements org.omg.CORBA.portable.Streamable
{
  public Sem6Lab5.Taskable value = null;

  public TaskableHolder ()
  {
  }

  public TaskableHolder (Sem6Lab5.Taskable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Sem6Lab5.TaskableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Sem6Lab5.TaskableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Sem6Lab5.TaskableHelper.type ();
  }

}
