package Sem6Lab5;


/**
* Sem6Lab5/TaskablePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sem6Lab5.idl
* 12 апреля 2019 г. 14:19:27 MSK
*/

public abstract class TaskablePOA extends org.omg.PortableServer.Servant
 implements Sem6Lab5.TaskableOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getResult", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Sem6Lab5/Taskable/getResult
       {
         String $result = null;
         $result = this.getResult ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Sem6Lab5/Taskable:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Taskable _this() 
  {
    return TaskableHelper.narrow(
    super._this_object());
  }

  public Taskable _this(org.omg.CORBA.ORB orb) 
  {
    return TaskableHelper.narrow(
    super._this_object(orb));
  }


} // class TaskablePOA
